In [1]:
import numpy as np

In [27]:
a=np.array(["a","b","c"])

In [5]:
x=np.array(["4.2"],dtype="int32") 

ValueError: invalid literal for int() with base 10: '4.2'

In [7]:
float("4.2")

4.2

In [20]:
a=np.zeros((1,2,2,4))

In [26]:
a[0][0].shape

(2, 4)

In [50]:
np.full()

array(['c', 'b', 'a'], dtype='<U1')

In [5]:
np.random.normal(1,0.01,(4,5))

array([[0.99432804, 0.99731508, 1.00672576, 0.98359358, 1.00218516],
       [0.98732337, 1.00657559, 1.00224264, 1.00514565, 1.01021829],
       [0.99454141, 1.01475423, 0.98635294, 1.00072461, 1.01008003],
       [1.01051841, 0.99616804, 0.99088895, 0.98672413, 0.99958539]])

In [7]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [8]:
a=np.array([1,2,3])
b=np.array([1,2,3])
a*b

array([1, 4, 9])

In [2]:
a=np.arange(11)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a.shape

(11,)

In [9]:
a[np.newaxis,:].shape

(1, 11)

In [7]:
a[:,None].shape

(11, 1)

In [8]:
np.newaxis

In [10]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
b=np.arange(11,22)

In [15]:
b.size

11

In [13]:
a.size

11

In [17]:
np.vstack([a,b]).shape

(2, 11)

In [22]:
np.concatenate([a,b],axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [19]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])